// flow-typed signature: e89e2f4da1c0218d601702af52bfcfa7
// flow-typed version: <<STUB>>/chai-jquery_v^2.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-jquery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-jquery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai-jquery/chai-jquery' {
  declare module.exports: any;
}

declare module 'chai-jquery/test/chai-jquery-spec' {
  declare module.exports: any;
}

declare module 'chai-jquery/test/jquery-inspect-spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai-jquery/chai-jquery.js' {
  declare module.exports: $Exports<'chai-jquery/chai-jquery'>;
}
declare module 'chai-jquery/test/chai-jquery-spec.js' {
  declare module.exports: $Exports<'chai-jquery/test/chai-jquery-spec'>;
}
declare module 'chai-jquery/test/jquery-inspect-spec.js' {
  declare module.exports: $Exports<'chai-jquery/test/jquery-inspect-spec'>;
}
