// flow-typed signature: 3a3a34e13237b338ab5c6d8f2a0fe91e
// flow-typed version: <<STUB>>/filehound_v^1.16.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'filehound'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'filehound' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'filehound/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'filehound/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'filehound/docconfig/template/publish' {
  declare module.exports: any;
}

declare module 'filehound/docconfig/template/static/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'filehound/docconfig/template/static/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'filehound/docconfig/template/static/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'filehound/docs/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'filehound/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'filehound/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'filehound/lib/arrays' {
  declare module.exports: any;
}

declare module 'filehound/lib/filehound' {
  declare module.exports: any;
}

declare module 'filehound/lib/files' {
  declare module.exports: any;
}

declare module 'filehound/lib/functions' {
  declare module.exports: any;
}

declare module 'filehound/test/filehound' {
  declare module.exports: any;
}

declare module 'filehound/test/files' {
  declare module.exports: any;
}

// Filename aliases
declare module 'filehound/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'filehound/coverage/lcov-report/prettify'>;
}
declare module 'filehound/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'filehound/coverage/lcov-report/sorter'>;
}
declare module 'filehound/docconfig/template/publish.js' {
  declare module.exports: $Exports<'filehound/docconfig/template/publish'>;
}
declare module 'filehound/docconfig/template/static/scripts/linenumber.js' {
  declare module.exports: $Exports<'filehound/docconfig/template/static/scripts/linenumber'>;
}
declare module 'filehound/docconfig/template/static/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'filehound/docconfig/template/static/scripts/prettify/lang-css'>;
}
declare module 'filehound/docconfig/template/static/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'filehound/docconfig/template/static/scripts/prettify/prettify'>;
}
declare module 'filehound/docs/scripts/linenumber.js' {
  declare module.exports: $Exports<'filehound/docs/scripts/linenumber'>;
}
declare module 'filehound/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'filehound/docs/scripts/prettify/lang-css'>;
}
declare module 'filehound/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'filehound/docs/scripts/prettify/prettify'>;
}
declare module 'filehound/index' {
  declare module.exports: $Exports<'filehound'>;
}
declare module 'filehound/index.js' {
  declare module.exports: $Exports<'filehound'>;
}
declare module 'filehound/lib/arrays.js' {
  declare module.exports: $Exports<'filehound/lib/arrays'>;
}
declare module 'filehound/lib/filehound.js' {
  declare module.exports: $Exports<'filehound/lib/filehound'>;
}
declare module 'filehound/lib/files.js' {
  declare module.exports: $Exports<'filehound/lib/files'>;
}
declare module 'filehound/lib/functions.js' {
  declare module.exports: $Exports<'filehound/lib/functions'>;
}
declare module 'filehound/test/filehound.js' {
  declare module.exports: $Exports<'filehound/test/filehound'>;
}
declare module 'filehound/test/files.js' {
  declare module.exports: $Exports<'filehound/test/files'>;
}
