// flow-typed signature: 4f49c33aebeb521b0b1e5db72a8f0fb2
// flow-typed version: <<STUB>>/postcss-modules-parser_v^1.1.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-modules-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-modules-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-modules-parser/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-modules-parser/index' {
  declare module.exports: $Exports<'postcss-modules-parser'>;
}
declare module 'postcss-modules-parser/index.js' {
  declare module.exports: $Exports<'postcss-modules-parser'>;
}
declare module 'postcss-modules-parser/lib/index.js' {
  declare module.exports: $Exports<'postcss-modules-parser/lib/index'>;
}
