// flow-typed signature: a5c1eccb890970e89e6df665e79b21c3
// flow-typed version: <<STUB>>/poststylus_v^0.2.3/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'poststylus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'poststylus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'poststylus/index' {
  declare module.exports: $Exports<'poststylus'>;
}
declare module 'poststylus/index.js' {
  declare module.exports: $Exports<'poststylus'>;
}
