// flow-typed signature: 08291036488aacdcf04998497b684a7c
// flow-typed version: <<STUB>>/prepend-style-loader_v^1.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prepend-style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'prepend-style-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prepend-style-loader/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prepend-style-loader/index' {
  declare module.exports: $Exports<'prepend-style-loader'>;
}
declare module 'prepend-style-loader/index.js' {
  declare module.exports: $Exports<'prepend-style-loader'>;
}
declare module 'prepend-style-loader/tests/index.js' {
  declare module.exports: $Exports<'prepend-style-loader/tests/index'>;
}
