// flow-typed signature: 02338f37008e30bda2d57cbf59a023d7
// flow-typed version: <<STUB>>/react-dom-stream_v^0.5.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dom-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dom-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dom-stream/build/lru-render-cache' {
  declare module.exports: any;
}

declare module 'react-dom-stream/dist/react-with-addons' {
  declare module.exports: any;
}

declare module 'react-dom-stream/dist/react-with-addons.min' {
  declare module.exports: any;
}

declare module 'react-dom-stream/dist/react' {
  declare module.exports: any;
}

declare module 'react-dom-stream/dist/react.min' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/accumulate' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/accumulateInto' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/adler32' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/AutoFocusUtils' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/BeforeInputEventPlugin' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/CallbackQueue' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/canDefineProperty' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ChangeEventPlugin' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ClientReactRootIndex' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/cloneWithProps' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/createHierarchyRenderer' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/CSSProperty' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/CSSPropertyOperations' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/Danger' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/dangerousStyleValue' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/DefaultEventPluginOrder' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/deprecated' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/DOMChildrenOperations' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/DOMProperty' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/DOMPropertyOperations' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/EnterLeaveEventPlugin' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/escapeTextContentForBrowser' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/EventConstants' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/EventPluginHub' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/EventPluginRegistry' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/EventPluginUtils' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/EventPropagators' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/FallbackCompositionState' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/findDOMNode' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/flattenChildren' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/forEachAccumulated' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/getEventCharCode' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/getEventKey' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/getEventModifierState' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/getEventTarget' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/getIteratorFn' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/getNodeForCharacterOffset' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/getTestDocument' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/getTextContentAccessor' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/HTMLDOMPropertyConfig' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/instantiateReactComponent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/isEventSupported' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/isReadableStream' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/isTextInputElement' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/LinkedStateMixin' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/LinkedValueUtils' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/MetaMatchers' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/Object.assign' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/onlyChild' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/OrderedMap' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/PooledClass' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/quoteAttributeValueForBrowser' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/React' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactBrowserComponentMixin' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactBrowserEventEmitter' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactChildReconciler' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactChildren' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactClass' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactComponent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactComponentBrowserEnvironment' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactComponentEnvironment' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/reactComponentExpect' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactComponentWithPureRenderMixin' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactCompositeComponent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactCSSTransitionGroup' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactCSSTransitionGroupChild' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactCurrentOwner' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDefaultBatchingStrategy' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDefaultInjection' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDefaultPerf' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDefaultPerfAnalysis' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDOM' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDOMButton' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDOMComponent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDOMFactories' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDOMFeatureFlags' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDOMIDOperations' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDOMInput' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDOMOption' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDOMSelect' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDOMSelection' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDOMServer' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDOMTextarea' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactDOMTextComponent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactElement' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactElementValidator' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactEmptyComponentRegistry' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactErrorUtils' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactEventEmitterMixin' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactEventListener' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactFragment' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactInjection' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactInputSelection' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactInstanceHandles' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactInstanceMap' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactIsomorphic' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactLink' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactMarkupChecksum' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactMount' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactMultiChild' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactMultiChildUpdateTypes' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactNativeComponent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactNoopUpdateQueue' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactOwner' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactPerf' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactPropTransferer' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactPropTypeLocationNames' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactPropTypeLocations' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactPropTypes' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactReconciler' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactReconcileTransaction' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactRef' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactRootIndex' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactServerAsyncRendering' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactServerBatchingStrategy' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactServerRendering' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactServerRenderingTransaction' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactStateSetters' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactTestUtils' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactTransitionChildMapping' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactTransitionEvents' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactTransitionGroup' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactUpdateQueue' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactUpdates' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactVersion' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ReactWithAddons' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/renderSubtreeIntoContainer' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ResponderEventPlugin' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ResponderSyntheticEvent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ResponderTouchHistoryStore' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/rollingAdler32' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/SelectEventPlugin' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ServerReactRootIndex' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/setInnerHTML' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/setTextContent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/shallowCompare' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/shouldUpdateReactComponent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/SimpleEventPlugin' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/sliceChildren' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/SVGDOMPropertyConfig' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/SyntheticClipboardEvent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/SyntheticCompositionEvent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/SyntheticDragEvent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/SyntheticEvent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/SyntheticFocusEvent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/SyntheticInputEvent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/SyntheticKeyboardEvent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/SyntheticMouseEvent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/SyntheticTouchEvent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/SyntheticUIEvent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/SyntheticWheelEvent' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/TapEventPlugin' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/Transaction' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/traverseAllChildren' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/update' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/validateDOMNesting' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/ViewportMetrics' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lib/webcomponents' {
  declare module.exports: any;
}

declare module 'react-dom-stream/lru-render-cache' {
  declare module.exports: any;
}

declare module 'react-dom-stream/modules/lru-render-cache' {
  declare module.exports: any;
}

declare module 'react-dom-stream/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dom-stream/build/lru-render-cache.js' {
  declare module.exports: $Exports<'react-dom-stream/build/lru-render-cache'>;
}
declare module 'react-dom-stream/dist/react-with-addons.js' {
  declare module.exports: $Exports<'react-dom-stream/dist/react-with-addons'>;
}
declare module 'react-dom-stream/dist/react-with-addons.min.js' {
  declare module.exports: $Exports<'react-dom-stream/dist/react-with-addons.min'>;
}
declare module 'react-dom-stream/dist/react.js' {
  declare module.exports: $Exports<'react-dom-stream/dist/react'>;
}
declare module 'react-dom-stream/dist/react.min.js' {
  declare module.exports: $Exports<'react-dom-stream/dist/react.min'>;
}
declare module 'react-dom-stream/index' {
  declare module.exports: $Exports<'react-dom-stream'>;
}
declare module 'react-dom-stream/index.js' {
  declare module.exports: $Exports<'react-dom-stream'>;
}
declare module 'react-dom-stream/lib/accumulate.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/accumulate'>;
}
declare module 'react-dom-stream/lib/accumulateInto.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/accumulateInto'>;
}
declare module 'react-dom-stream/lib/adler32.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/adler32'>;
}
declare module 'react-dom-stream/lib/AutoFocusUtils.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/AutoFocusUtils'>;
}
declare module 'react-dom-stream/lib/BeforeInputEventPlugin.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/BeforeInputEventPlugin'>;
}
declare module 'react-dom-stream/lib/CallbackQueue.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/CallbackQueue'>;
}
declare module 'react-dom-stream/lib/canDefineProperty.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/canDefineProperty'>;
}
declare module 'react-dom-stream/lib/ChangeEventPlugin.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ChangeEventPlugin'>;
}
declare module 'react-dom-stream/lib/ClientReactRootIndex.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ClientReactRootIndex'>;
}
declare module 'react-dom-stream/lib/cloneWithProps.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/cloneWithProps'>;
}
declare module 'react-dom-stream/lib/createHierarchyRenderer.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/createHierarchyRenderer'>;
}
declare module 'react-dom-stream/lib/CSSProperty.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/CSSProperty'>;
}
declare module 'react-dom-stream/lib/CSSPropertyOperations.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/CSSPropertyOperations'>;
}
declare module 'react-dom-stream/lib/Danger.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/Danger'>;
}
declare module 'react-dom-stream/lib/dangerousStyleValue.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/dangerousStyleValue'>;
}
declare module 'react-dom-stream/lib/DefaultEventPluginOrder.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/DefaultEventPluginOrder'>;
}
declare module 'react-dom-stream/lib/deprecated.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/deprecated'>;
}
declare module 'react-dom-stream/lib/DOMChildrenOperations.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/DOMChildrenOperations'>;
}
declare module 'react-dom-stream/lib/DOMProperty.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/DOMProperty'>;
}
declare module 'react-dom-stream/lib/DOMPropertyOperations.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/DOMPropertyOperations'>;
}
declare module 'react-dom-stream/lib/EnterLeaveEventPlugin.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/EnterLeaveEventPlugin'>;
}
declare module 'react-dom-stream/lib/escapeTextContentForBrowser.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/escapeTextContentForBrowser'>;
}
declare module 'react-dom-stream/lib/EventConstants.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/EventConstants'>;
}
declare module 'react-dom-stream/lib/EventPluginHub.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/EventPluginHub'>;
}
declare module 'react-dom-stream/lib/EventPluginRegistry.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/EventPluginRegistry'>;
}
declare module 'react-dom-stream/lib/EventPluginUtils.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/EventPluginUtils'>;
}
declare module 'react-dom-stream/lib/EventPropagators.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/EventPropagators'>;
}
declare module 'react-dom-stream/lib/FallbackCompositionState.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/FallbackCompositionState'>;
}
declare module 'react-dom-stream/lib/findDOMNode.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/findDOMNode'>;
}
declare module 'react-dom-stream/lib/flattenChildren.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/flattenChildren'>;
}
declare module 'react-dom-stream/lib/forEachAccumulated.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/forEachAccumulated'>;
}
declare module 'react-dom-stream/lib/getEventCharCode.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/getEventCharCode'>;
}
declare module 'react-dom-stream/lib/getEventKey.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/getEventKey'>;
}
declare module 'react-dom-stream/lib/getEventModifierState.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/getEventModifierState'>;
}
declare module 'react-dom-stream/lib/getEventTarget.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/getEventTarget'>;
}
declare module 'react-dom-stream/lib/getIteratorFn.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/getIteratorFn'>;
}
declare module 'react-dom-stream/lib/getNodeForCharacterOffset.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/getNodeForCharacterOffset'>;
}
declare module 'react-dom-stream/lib/getTestDocument.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/getTestDocument'>;
}
declare module 'react-dom-stream/lib/getTextContentAccessor.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/getTextContentAccessor'>;
}
declare module 'react-dom-stream/lib/HTMLDOMPropertyConfig.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/HTMLDOMPropertyConfig'>;
}
declare module 'react-dom-stream/lib/instantiateReactComponent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/instantiateReactComponent'>;
}
declare module 'react-dom-stream/lib/isEventSupported.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/isEventSupported'>;
}
declare module 'react-dom-stream/lib/isReadableStream.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/isReadableStream'>;
}
declare module 'react-dom-stream/lib/isTextInputElement.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/isTextInputElement'>;
}
declare module 'react-dom-stream/lib/LinkedStateMixin.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/LinkedStateMixin'>;
}
declare module 'react-dom-stream/lib/LinkedValueUtils.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/LinkedValueUtils'>;
}
declare module 'react-dom-stream/lib/MetaMatchers.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/MetaMatchers'>;
}
declare module 'react-dom-stream/lib/Object.assign.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/Object.assign'>;
}
declare module 'react-dom-stream/lib/onlyChild.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/onlyChild'>;
}
declare module 'react-dom-stream/lib/OrderedMap.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/OrderedMap'>;
}
declare module 'react-dom-stream/lib/PooledClass.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/PooledClass'>;
}
declare module 'react-dom-stream/lib/quoteAttributeValueForBrowser.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/quoteAttributeValueForBrowser'>;
}
declare module 'react-dom-stream/lib/React.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/React'>;
}
declare module 'react-dom-stream/lib/ReactBrowserComponentMixin.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactBrowserComponentMixin'>;
}
declare module 'react-dom-stream/lib/ReactBrowserEventEmitter.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactBrowserEventEmitter'>;
}
declare module 'react-dom-stream/lib/ReactChildReconciler.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactChildReconciler'>;
}
declare module 'react-dom-stream/lib/ReactChildren.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactChildren'>;
}
declare module 'react-dom-stream/lib/ReactClass.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactClass'>;
}
declare module 'react-dom-stream/lib/ReactComponent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactComponent'>;
}
declare module 'react-dom-stream/lib/ReactComponentBrowserEnvironment.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactComponentBrowserEnvironment'>;
}
declare module 'react-dom-stream/lib/ReactComponentEnvironment.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactComponentEnvironment'>;
}
declare module 'react-dom-stream/lib/reactComponentExpect.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/reactComponentExpect'>;
}
declare module 'react-dom-stream/lib/ReactComponentWithPureRenderMixin.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactComponentWithPureRenderMixin'>;
}
declare module 'react-dom-stream/lib/ReactCompositeComponent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactCompositeComponent'>;
}
declare module 'react-dom-stream/lib/ReactCSSTransitionGroup.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactCSSTransitionGroup'>;
}
declare module 'react-dom-stream/lib/ReactCSSTransitionGroupChild.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactCSSTransitionGroupChild'>;
}
declare module 'react-dom-stream/lib/ReactCurrentOwner.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactCurrentOwner'>;
}
declare module 'react-dom-stream/lib/ReactDefaultBatchingStrategy.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDefaultBatchingStrategy'>;
}
declare module 'react-dom-stream/lib/ReactDefaultInjection.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDefaultInjection'>;
}
declare module 'react-dom-stream/lib/ReactDefaultPerf.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDefaultPerf'>;
}
declare module 'react-dom-stream/lib/ReactDefaultPerfAnalysis.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDefaultPerfAnalysis'>;
}
declare module 'react-dom-stream/lib/ReactDOM.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDOM'>;
}
declare module 'react-dom-stream/lib/ReactDOMButton.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDOMButton'>;
}
declare module 'react-dom-stream/lib/ReactDOMComponent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDOMComponent'>;
}
declare module 'react-dom-stream/lib/ReactDOMFactories.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDOMFactories'>;
}
declare module 'react-dom-stream/lib/ReactDOMFeatureFlags.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDOMFeatureFlags'>;
}
declare module 'react-dom-stream/lib/ReactDOMIDOperations.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDOMIDOperations'>;
}
declare module 'react-dom-stream/lib/ReactDOMInput.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDOMInput'>;
}
declare module 'react-dom-stream/lib/ReactDOMOption.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDOMOption'>;
}
declare module 'react-dom-stream/lib/ReactDOMSelect.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDOMSelect'>;
}
declare module 'react-dom-stream/lib/ReactDOMSelection.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDOMSelection'>;
}
declare module 'react-dom-stream/lib/ReactDOMServer.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDOMServer'>;
}
declare module 'react-dom-stream/lib/ReactDOMTextarea.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDOMTextarea'>;
}
declare module 'react-dom-stream/lib/ReactDOMTextComponent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactDOMTextComponent'>;
}
declare module 'react-dom-stream/lib/ReactElement.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactElement'>;
}
declare module 'react-dom-stream/lib/ReactElementValidator.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactElementValidator'>;
}
declare module 'react-dom-stream/lib/ReactEmptyComponent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactEmptyComponent'>;
}
declare module 'react-dom-stream/lib/ReactEmptyComponentRegistry.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactEmptyComponentRegistry'>;
}
declare module 'react-dom-stream/lib/ReactErrorUtils.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactErrorUtils'>;
}
declare module 'react-dom-stream/lib/ReactEventEmitterMixin.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactEventEmitterMixin'>;
}
declare module 'react-dom-stream/lib/ReactEventListener.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactEventListener'>;
}
declare module 'react-dom-stream/lib/ReactFragment.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactFragment'>;
}
declare module 'react-dom-stream/lib/ReactInjection.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactInjection'>;
}
declare module 'react-dom-stream/lib/ReactInputSelection.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactInputSelection'>;
}
declare module 'react-dom-stream/lib/ReactInstanceHandles.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactInstanceHandles'>;
}
declare module 'react-dom-stream/lib/ReactInstanceMap.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactInstanceMap'>;
}
declare module 'react-dom-stream/lib/ReactIsomorphic.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactIsomorphic'>;
}
declare module 'react-dom-stream/lib/ReactLink.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactLink'>;
}
declare module 'react-dom-stream/lib/ReactMarkupChecksum.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactMarkupChecksum'>;
}
declare module 'react-dom-stream/lib/ReactMount.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactMount'>;
}
declare module 'react-dom-stream/lib/ReactMultiChild.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactMultiChild'>;
}
declare module 'react-dom-stream/lib/ReactMultiChildUpdateTypes.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactMultiChildUpdateTypes'>;
}
declare module 'react-dom-stream/lib/ReactNativeComponent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactNativeComponent'>;
}
declare module 'react-dom-stream/lib/ReactNoopUpdateQueue.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactNoopUpdateQueue'>;
}
declare module 'react-dom-stream/lib/ReactOwner.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactOwner'>;
}
declare module 'react-dom-stream/lib/ReactPerf.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactPerf'>;
}
declare module 'react-dom-stream/lib/ReactPropTransferer.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactPropTransferer'>;
}
declare module 'react-dom-stream/lib/ReactPropTypeLocationNames.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactPropTypeLocationNames'>;
}
declare module 'react-dom-stream/lib/ReactPropTypeLocations.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactPropTypeLocations'>;
}
declare module 'react-dom-stream/lib/ReactPropTypes.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactPropTypes'>;
}
declare module 'react-dom-stream/lib/ReactReconciler.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactReconciler'>;
}
declare module 'react-dom-stream/lib/ReactReconcileTransaction.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactReconcileTransaction'>;
}
declare module 'react-dom-stream/lib/ReactRef.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactRef'>;
}
declare module 'react-dom-stream/lib/ReactRootIndex.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactRootIndex'>;
}
declare module 'react-dom-stream/lib/ReactServerAsyncRendering.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactServerAsyncRendering'>;
}
declare module 'react-dom-stream/lib/ReactServerBatchingStrategy.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactServerBatchingStrategy'>;
}
declare module 'react-dom-stream/lib/ReactServerRendering.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactServerRendering'>;
}
declare module 'react-dom-stream/lib/ReactServerRenderingTransaction.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactServerRenderingTransaction'>;
}
declare module 'react-dom-stream/lib/ReactStateSetters.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactStateSetters'>;
}
declare module 'react-dom-stream/lib/ReactTestUtils.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactTestUtils'>;
}
declare module 'react-dom-stream/lib/ReactTransitionChildMapping.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactTransitionChildMapping'>;
}
declare module 'react-dom-stream/lib/ReactTransitionEvents.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactTransitionEvents'>;
}
declare module 'react-dom-stream/lib/ReactTransitionGroup.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactTransitionGroup'>;
}
declare module 'react-dom-stream/lib/ReactUpdateQueue.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactUpdateQueue'>;
}
declare module 'react-dom-stream/lib/ReactUpdates.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactUpdates'>;
}
declare module 'react-dom-stream/lib/ReactVersion.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactVersion'>;
}
declare module 'react-dom-stream/lib/ReactWithAddons.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ReactWithAddons'>;
}
declare module 'react-dom-stream/lib/renderSubtreeIntoContainer.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/renderSubtreeIntoContainer'>;
}
declare module 'react-dom-stream/lib/ResponderEventPlugin.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ResponderEventPlugin'>;
}
declare module 'react-dom-stream/lib/ResponderSyntheticEvent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ResponderSyntheticEvent'>;
}
declare module 'react-dom-stream/lib/ResponderTouchHistoryStore.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ResponderTouchHistoryStore'>;
}
declare module 'react-dom-stream/lib/rollingAdler32.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/rollingAdler32'>;
}
declare module 'react-dom-stream/lib/SelectEventPlugin.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/SelectEventPlugin'>;
}
declare module 'react-dom-stream/lib/ServerReactRootIndex.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ServerReactRootIndex'>;
}
declare module 'react-dom-stream/lib/setInnerHTML.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/setInnerHTML'>;
}
declare module 'react-dom-stream/lib/setTextContent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/setTextContent'>;
}
declare module 'react-dom-stream/lib/shallowCompare.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/shallowCompare'>;
}
declare module 'react-dom-stream/lib/shouldUpdateReactComponent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/shouldUpdateReactComponent'>;
}
declare module 'react-dom-stream/lib/SimpleEventPlugin.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/SimpleEventPlugin'>;
}
declare module 'react-dom-stream/lib/sliceChildren.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/sliceChildren'>;
}
declare module 'react-dom-stream/lib/SVGDOMPropertyConfig.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/SVGDOMPropertyConfig'>;
}
declare module 'react-dom-stream/lib/SyntheticClipboardEvent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/SyntheticClipboardEvent'>;
}
declare module 'react-dom-stream/lib/SyntheticCompositionEvent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/SyntheticCompositionEvent'>;
}
declare module 'react-dom-stream/lib/SyntheticDragEvent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/SyntheticDragEvent'>;
}
declare module 'react-dom-stream/lib/SyntheticEvent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/SyntheticEvent'>;
}
declare module 'react-dom-stream/lib/SyntheticFocusEvent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/SyntheticFocusEvent'>;
}
declare module 'react-dom-stream/lib/SyntheticInputEvent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/SyntheticInputEvent'>;
}
declare module 'react-dom-stream/lib/SyntheticKeyboardEvent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/SyntheticKeyboardEvent'>;
}
declare module 'react-dom-stream/lib/SyntheticMouseEvent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/SyntheticMouseEvent'>;
}
declare module 'react-dom-stream/lib/SyntheticTouchEvent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/SyntheticTouchEvent'>;
}
declare module 'react-dom-stream/lib/SyntheticUIEvent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/SyntheticUIEvent'>;
}
declare module 'react-dom-stream/lib/SyntheticWheelEvent.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/SyntheticWheelEvent'>;
}
declare module 'react-dom-stream/lib/TapEventPlugin.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/TapEventPlugin'>;
}
declare module 'react-dom-stream/lib/Transaction.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/Transaction'>;
}
declare module 'react-dom-stream/lib/traverseAllChildren.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/traverseAllChildren'>;
}
declare module 'react-dom-stream/lib/update.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/update'>;
}
declare module 'react-dom-stream/lib/validateDOMNesting.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/validateDOMNesting'>;
}
declare module 'react-dom-stream/lib/ViewportMetrics.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/ViewportMetrics'>;
}
declare module 'react-dom-stream/lib/webcomponents.js' {
  declare module.exports: $Exports<'react-dom-stream/lib/webcomponents'>;
}
declare module 'react-dom-stream/lru-render-cache.js' {
  declare module.exports: $Exports<'react-dom-stream/lru-render-cache'>;
}
declare module 'react-dom-stream/modules/lru-render-cache.js' {
  declare module.exports: $Exports<'react-dom-stream/modules/lru-render-cache'>;
}
declare module 'react-dom-stream/server.js' {
  declare module.exports: $Exports<'react-dom-stream/server'>;
}
